### ISSUE TITLE
Posible to restore some_db from pg_backup to another working postgresdb

### ISSUE THREAD

**Issue by glafir** [postgrespro/pg_probackup#353]
Do you have possibility to restore some_db from pg_backup to another working postgresdb. For example

PG00 - 1st postgres-db. It has some 3 dbs (db0, db1, db2) and backups.
PG01 - 2nd postgres-db. It has some amother 3 dbs (db3, db4, db5).

Can I restore `db0` from `PG00` to `PG01` for example.  But I want to Leave as is
 dbs on `PG01`.

The result expect which db0, db3, db4, db5 are state in `PG01`

**Comment by gsmol** [comment]
Hello!
No, it is impossible, because databases in PG cluster are not truly separate entities, the use a lot of common infrastructure:
1. transaction log, so it is impossible to just shove the database in cluster, data in new databse will be impossible to access.
2. WAL, impossible to glue totheger WAL for new database and WAL for existing
3. global tablespace in pg_catalog, must be synchronized somehow between new database and existing cluster

**Comment by glafir** [comment]
Oh, Thanks!
