### ISSUE TITLE
validate failed: Cannot seek block 261889 

### ISSUE THREAD

**Issue by jackhz2012** [postgrespro/pg_probackup#588]
validate failed: Cannot seek block 261889 . 
when backupfile bigger than 2G, validate failed.error message : Cannot seek block 261889

**Comment by fukanchik** [comment]
Hi jackhz2012,
What is the pg_probackup version?

Are there specific steps which might help us reproduce the issue?

**Comment by jackhz2012** [comment]
pg_probackup 2.5.11 (PostgreSQL 10.12.X.9);
backup command :
pg_probackup backup -B /home/postgres/backup2/probackup --instance name1 -b full   --progress

**Comment by fukanchik** [comment]
I created a 3Gb file in $PGDATA and was able to successfully backup/validate/show/restore it. No problem for me.

In what situation does this happen for you? Does it always fail? ...or in some specific circumstance?

**Comment by fukanchik** [comment]
I also tried it over SSH and it worked ok.

**Comment by Burus** [comment]
@jackhz2012 The server from which the backup was taken and the restored server must be compatible by the [block_size](https://postgrespro.com/docs/postgresql/current/runtime-config-preset#GUC-BLOCK-SIZE) and [wal_block_size](https://postgrespro.com/docs/postgresql/current/runtime-config-preset#GUC-WAL-BLOCK-SIZE) parameters and have the same major release number.

Please, show us more information about yours build configuration for the Postgres and pg_probackup.

**Comment by funny-falcon** [comment]
@jackhz2012 Do I understand right: you're trying pg_probackup on PostgreSQL's fork with not standard 1GB datafile segment or wal segment greater than 1GB?

We don't deal with such strange forks at the moment. Unfortunately, we have several int32 fields in binary format, and doubtfully it could be easily fixed.

Probably next major version (3.x) will be capable to do it since we could change storage format. But I wouldn't promise any date of its release.
