### ISSUE TITLE
Single database backup

### ISSUE THREAD

**Issue by MiyamuraMiyako** [postgrespro/pg_probackup#595]
It seems `pg_probackup` backup operation is all databases scope. Is there a way to backup or restore a single database without affecting other databases and without downtime?

**Comment by Burus** [comment]
The main root cause is PostgreSQL cluster architecture with numerous databases in one instance. 

No it's dangerous and we cant do backup for single DB right now.  

You can try to use our **partial restore** features with flags "resrtore --db-exclude" (https://postgrespro.ru/docs/postgrespro/15/app-pgprobackup?lang=en) from full backup or make another architecture for your backend with different databases in each PostgreSQL.
